### ISSUE TITLE
Readmen & repon viilaaminen paremmaksi (1h)

### ISSUE THREAD

**Issue by PPeltola** [Ohjelmistotuotanto-DoD/vinkr#30]
Buildausohjeet (ja buildi repoon), paremmat käyttöohjeet, repoon release demottavasta versiosta

**Comment by pprepu** [comment]
Readme vois sisältää sen ohjeen (tulevan releasen sisältämän) jar-tiedoston ajamiseks, mut muuten se vaikuttaa ihan hyvältä?

**Comment by pprepu** [comment]
laitoin itelleni taskin releasen tekemisestä, joten kun oon tehnyt sen niin voin ite lisätä linkin ja ohjeet readmehen.
