### ISSUE TITLE
Lisää ISBNTuonti-luokkaan staattinen metodi, joka luo uuden KirjaVinkki-objektin hakemansa JSON-objektin perusteella (1h)

### ISSUE THREAD

**Issue by vmarttil** [Ohjelmistotuotanto-DoD/vinkr#60]

**Comment by FINDarkside** [comment]
Mihin käyttötarkotukseen? Kun se tallennetaan taulukkona olioita, niin ei sitä kannata manuaalisesti rupee parsimaan et sieltä sais yksittäisten olioitten jsonia ulos. Eikä sitä jsonia muutenkaan kannata manuaalisesti parsia konstruktorissakaan, kun se on sen json serialisointi kirjaston tehtävä luoda se luokka ja asettaa kentät oikein. Siihen tarvii vaan [yhen rivin](https://github.com/Ohjelmistotuotanto-DoD/vinkr/blob/master/src/main/java/vinkr/Vinkr.java#L15) minkä jälkeen on ne oikeet oliot oikeilla kentillä parsittu jsonista.

**Comment by FINDarkside** [comment]
Aivan, tota ISBN juttuu varten, unoha toi ylläoleva 😄 . Kantsii ehkä tehdä mieluummin joku staattinen metodi mikä luo sen kirjavinkin, koska sit sen voi nimetä järkevästi. Sielt apista tulevan jsonin kentät ei oo saman nimisiä niitten meiän kenttien kanssa ni se vois olla vähän hämäävää jos konstruktori ottais jsonia jossain hassussa muodossa. Ite ainakin olettaisin että jos on tollanen konstruktori niin se json mitä sinne annetaan on siinä muodossa mitä saa kun sen olion muuttaa jsoniksi.

**Comment by vmarttil** [comment]
Hyvä pointti tosta staattisesta metodista; parempi tehdä tosiaan staattinen metodi joka kaivaa tarvittavat tiedot sieltä JSON-oliosta ja luo sen KirjaVinkki-olion ihan normaalia konstruktoria käyttäen.
