### ISSUE TITLE
Cucumber testit user-storylle: "Käyttäjä voi syöttää komennon ensimmäiset kirjaimet, jonka jälkeen ohjelma täydentää komennon loppuosan automaattisesti"

### ISSUE THREAD

**Issue by pprepu** [Ohjelmistotuotanto-DoD/vinkr#83]

**Comment by FINDarkside** [comment]
Tän testaaminen tuskin onnistuu mitenkään hirveen fiksusti. Autocomplete ei ees toimi kun ohjelmaa ajaa `gradle run`, mutta toimii jarissa.

**Comment by pprepu** [comment]
Kuten yllä todetaan, autocomplete toimii ainoastaan jarissa, joten cucumber -testit jätettiin tekemättä.
